name: Build and Test .NET 8 Application

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Wait for SQL Server
      run: |
        echo "Waiting for SQL Server to be ready..."
        for /L %%i in (1, 60, 1) do (
          sqlcmd -S localhost -U sa -P "YourStrong!Password" -Q "SELECT 1" && exit /b 0
          timeout /t 1 >nul
        )
        exit /b 1

    - name: Apply Database Migrations
      env:
        ConnectionStrings__DefaultConnection: "Server=localhost;Database=ContatosRegionais_Test;User Id=fiap;Password=123Mudar@Fiap02!;"
      run: dotnet ef database update

    - name: Build the application
      run: dotnet build --no-restore --configuration Release

    - name: Run unit tests
      run: dotnet test --no-build --configuration Release --logger trx