name: FASE 2 - Desenvolvimento - Build e Tests - CI

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "123Mudar@Fiap02!"
        ports: 
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Configure Kerberos
      #  run: |
      #    echo "[realms]" >> /etc/krb5.conf
      #    echo "example.com" = {" >> /etc/krb5.conf
      #    echo " kdc = kdc.example.com" >> /etch/krb5.conf
      #    echo " admin_server = admin.example.com" >> /etc/krb5.conf
      #    echo "}" >> /etc/krb5.conf
      #  shell: bash

      #- name: Initialize Kerberos
      #  run: |
      #    kinit -V -k -t /path/to/keytab user@localhost
      #    klist # valida os tickets ativos
      #  shell: bash

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Configure cache nuget
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            nuget-${{runner.os}} -

      - name: Restore dependencies
        #run: dotnet build --configuration Release --no-restore
        run: dotnet restore

      - name: Build solution - Contatos Regionais
        run: dotnet build -c Release --no-restore

      - name: Waiting SQL Server ready
        run: |
          for i in (1..30) do
            /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa -P '123Mudar@Fiap02!' -Q "SELECT 1" && break
            echo "Aguardando SQL Server iniciar..."
            sleep 2
          done

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef --version 8.0.11
          
      - name: Add .Net tools to Path
        run: | 
          echo "$(dotnet tool path)/bin" >> $GITHUB_PATH

      - name: Apply EF Migrations
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=ContatosRegionais;User Id=sa;Password=123Mudar@Fiap02!;TrustServerCertificate=True;Encrypt=False;Integrated Security=False;"
          working-directory: ./ContatosRegionais
        run: dotnet ef database update --project ./ContatosRegionais/ContatosRegionais.csproj

      - name: Run tests -Contatos Regionais
        run: dotnet test -c Debug --no-build --verbosity normal