name: FASE 2 - Desenvolvimento - Build e Tests - CI

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "123Mudar@Fiap02!"
        ports: 
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef --version 8.0.11
          
      - name: Add .Net tools to Path
        run: | 
          echo "$(dotnet tool path)/bin" >> $GITHUB_PATH

      - name: Restore dependencies
        #run: dotnet build --configuration Release --no-restore
        run: dotnet restore

      - name: Build solution - Contatos Regionais
        run: dotnet build -c Release --no-restore

      - name: Apply EF Migrations
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=ContatosRegionais;User Id=sa;Password=123Mudar@Fiap02!;"
          working-directory: ./ContatosRegionais
        run: dotnet ef database update

      - name: Run tests -Contatos Regionais
        run: dotnet test -c Debug --no-build --verbosity normal